/**
 * Sample React Native App
 *
 * adapted from App.js generated by the following command:
 *
 * react-native init example
 *
 * https://github.com/facebook/react-native
 */

import React, {Component} from 'react';
import {Platform, StyleSheet, Text, View, Button} from 'react-native';
import NativeLogger from 'react-native-native-logger';

export default class App extends Component<{}> {
  state = {
    count: 0,
  };

  incrementAndLog = () => {
    const newCount = this.state.count + 1;
    this.setState({count: newCount}, () => {
      NativeLogger.log(newCount);
      NativeLogger.log(this.state);
    });
  };

  render() {
    return (
      <View style={styles.container}>
        <Text style={styles.welcome}>{this.state.count}</Text>
        <Button title="press" onPress={this.incrementAndLog} />
      </View>
    );
  }
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#F5FCFF',
  },
  welcome: {
    fontSize: 20,
    textAlign: 'center',
    margin: 10,
  },
});
